default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 6 } %>

development:
  <<: *default
  database: astrum_development

test:
  <<: *default
  database: astrum_test

production:
  <<: *default
  database: astrum_production
  username: astrum
  password: <%= ENV['ASTRUM_DATABASE_PASSWORD'] %>
